### ISSUE TITLE
Official website is offline

### ISSUE THREAD

**Issue by ryuran** [at-import/SassyLists#57]
http://sassylists.com/
Everything is in the title.

**Comment by HugoGiraudel** [comment]
Yes, I don’t own the domain anymore. :D

**Comment by ryuran** [comment]
You can keep github-page url and change broken links in the readme.

**Comment by HugoGiraudel** [comment]
Can’t see any broken link?

**Comment by ryuran** [comment]
Ho yes, links are OK but github page redirect http://at-import.github.io/SassyLists to  http://sassylists.com/ or http://ww7.sassylists.com/

**Comment by HugoGiraudel** [comment]
That’s very odd. There is no CNAME anymore.

**Comment by HugoGiraudel** [comment]
Oh there was.
