### ISSUE TITLE
NPM build is broken

### ISSUE THREAD

**Issue by ncoden** [at-import/SassyLists#59]
The current npm build command includes `/stylesheets/_SassyLists.scss`. It contains all the `@import` statements and thus generates an invalid dist file.

How did you compiled the latest `dist/_SassyLists.scss` for the `v3.0.0` ?

**Comment by HugoGiraudel** [comment]
Oh. I guess we should make sure npm publishes the dist file. Didn’t realise you wanted to use it like this. I can’t do that now, so I’ll tackle this some time at the end of the week-end.

**Comment by ncoden** [comment]
I don't want to use it like this, but I want to compile Foundation to `dist/foundation.scss` too and don't know how to do it properly.

My solution for now is to concatenate source files without the main file containing the `@import`s statements. But it only works because no source file is using `@import`.

**Comment by ncoden** [comment]
@HugoGiraudel See: https://github.com/ncoden/gulp-shopify-sass ;)

**Comment by HugoGiraudel** [comment]
Okay so, what do we do about this? I don’t want to bring Gulp in there.

**Comment by ncoden** [comment]
You can:
- Continue to concatenate your files, but without the main `_SassyLists.scss`. It only works because you do not have `@import` statements in your partials.
- Use `gulp-shopify-sass-. It is by far the proper solution.
- Do not compile to a dist file. You do not have dependencies to include it, so everyone can simply include `stylesheets/SassyLists`

**Comment by HugoGiraudel** [comment]
I don’t get it. Why isn’t https://github.com/at-import/SassyLists/blob/master/dist/_SassyLists.scss okay with you?

**Comment by ncoden** [comment]
It is okay. But I don't know how you built it, the `npm run build` command doesn't build _that_ file.

**Comment by HugoGiraudel** [comment]
It does.

```
rm -rf dist/ && mkdir dist/ && cat stylesheets/**/* > dist/_SassyLists.scss
```

**Comment by ncoden** [comment]
Yes, it does when I run the script alone, and not when I run the build command...

**Comment by HugoGiraudel** [comment]
Works fine here. Do you have an error?

**Comment by ncoden** [comment]
```
➜  SassyLists git:(master) ✗ rm -rf dist/ && mkdir dist/ && cat stylesheets/**/* > dist/_SassyLists.scss
cat: stylesheets/functions: Is a directory
cat: stylesheets/helpers: Is a directory
➜  SassyLists git:(master) ✗ cat dist/_SassyLists.scss | head -n 6
// SassyLists - A couple of advanced Sass list functions
//
// Official site: http://at-import.github.io/functions/
// Repository: https://github.com/at-import/functions/

@import 'helpers/missing-dependencies';
```

`stylesheets/_SassyLists.scss` is imported in `dist/_SassyLists.scss`, and it should not. It works fine with the npm build command. I find this weird.
